void test_pu_for-v9.39-40_mbias-63_passtrig_raw()
{
//=========Macro generated from canvas: c1/c1
//=========  (Mon Mar 13 19:00:57 2017) by ROOT version6.06/01
   TCanvas *c1 = new TCanvas("c1", "c1",65,52,700,500);
   c1->Range(-12.5,-273.525,112.5,2461.725);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1D *pileup_passtrig_nGoodPV_rawWeight__1 = new TH1D("pileup_passtrig_nGoodPV_rawWeight__1","",100,0,100);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(2,1);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(3,3);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(4,7);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(5,24);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(6,62);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(7,130);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(8,205);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(9,373);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(10,532);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(11,699);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(12,1072);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(13,1322);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(14,1453);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(15,1674);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(16,1813);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(17,2000);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(18,2084);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(19,2033);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(20,2077);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(21,1910);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(22,1844);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(23,1661);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(24,1542);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(25,1389);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(26,1265);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(27,1054);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(28,938);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(29,841);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(30,750);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(31,610);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(32,540);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(33,450);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(34,382);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(35,344);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(36,299);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(37,261);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(38,199);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(39,155);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(40,163);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(41,134);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(42,137);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(43,99);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(44,82);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(45,61);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(46,57);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(47,34);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(48,31);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(49,27);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(50,21);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(51,16);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(52,11);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(53,15);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(54,13);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(55,13);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(56,7);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(57,5);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(58,4);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(59,8);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(60,5);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(61,4);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(62,4);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(63,2);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(64,2);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(65,4);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(66,3);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(68,2);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(69,1);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(73,1);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(79,1);
   pileup_passtrig_nGoodPV_rawWeight__1->SetBinContent(84,1);
   pileup_passtrig_nGoodPV_rawWeight__1->SetEntries(34966);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *AText = ptstats->AddText("pileup_passtrig_nGoodPV_rawWeight");
   AText->SetTextSize(0.0368);
   AText = ptstats->AddText("Entries = 34966  ");
   AText = ptstats->AddText("Mean  =  20.57");
   AText = ptstats->AddText("Std Dev   =  7.728");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   pileup_passtrig_nGoodPV_rawWeight__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(pileup_passtrig_nGoodPV_rawWeight__1);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   pileup_passtrig_nGoodPV_rawWeight__1->SetLineColor(ci);
   pileup_passtrig_nGoodPV_rawWeight__1->GetXaxis()->SetLabelFont(42);
   pileup_passtrig_nGoodPV_rawWeight__1->GetXaxis()->SetLabelSize(0.035);
   pileup_passtrig_nGoodPV_rawWeight__1->GetXaxis()->SetTitleSize(0.035);
   pileup_passtrig_nGoodPV_rawWeight__1->GetXaxis()->SetTitleFont(42);
   pileup_passtrig_nGoodPV_rawWeight__1->GetYaxis()->SetLabelFont(42);
   pileup_passtrig_nGoodPV_rawWeight__1->GetYaxis()->SetLabelSize(0.035);
   pileup_passtrig_nGoodPV_rawWeight__1->GetYaxis()->SetTitleSize(0.035);
   pileup_passtrig_nGoodPV_rawWeight__1->GetYaxis()->SetTitleFont(42);
   pileup_passtrig_nGoodPV_rawWeight__1->GetZaxis()->SetLabelFont(42);
   pileup_passtrig_nGoodPV_rawWeight__1->GetZaxis()->SetLabelSize(0.035);
   pileup_passtrig_nGoodPV_rawWeight__1->GetZaxis()->SetTitleSize(0.035);
   pileup_passtrig_nGoodPV_rawWeight__1->GetZaxis()->SetTitleFont(42);
   pileup_passtrig_nGoodPV_rawWeight__1->Draw("");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
